import { StyleSheet, Dimensions } from 'react-native';
import { theme, glassStyles, commonStyles } from './theme';
import { goalsStyles } from './home/goals';
import { shoppingStyles } from './home/shopping';
import { appointmentsStyles } from './home/appointments';
import { attentionStyles } from './home/attention';

const { width, height } = Dimensions.get('window');

export const homeStyles = StyleSheet.create({
  // Basic container styles
  gradientContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent', // Transparent to show gradient
  },
  contentContainer: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  tabContentScrollView: {
    flex: 1,
  },
  
  // Split-out style modules
  ...shoppingStyles,
  ...goalsStyles,
  ...appointmentsStyles,
  ...attentionStyles,

  // Blog Slider
  blogSliderContainer: {
    marginTop: 8,
  },
  blogSliderContent: {
    paddingHorizontal: 4,
    paddingLeft: 16,
    paddingRight: 16,
  },
  blogCard: {
    width: 220,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.9)',
    marginRight: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  blogCardImageWrapper: {
    position: 'relative',
    width: '100%',
    height: 140,
  },
  blogCardImage: {
    width: '100%',
    height: '100%',
  },
  blogCardImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blogCardOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  blogCardTextOverlay: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
  },
  blogCardTitleOverlay: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  blogCardSubtitleOverlay: {
    marginTop: 4,
    fontSize: 12,
    color: '#F3F4F6',
  },
  
  // Header styles
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerLeft: {
    flex: 1,
  },
  headerLogo: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  assignedTaskButton: {
    position: 'relative',
    padding: 8,
    borderRadius: 20,
  },
  notificationButton: {
    position: 'relative',
    padding: 8,
    borderRadius: 20,
  },
  phoneButton: {
    padding: 8,
    borderRadius: 20,
  },
  notificationBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationText: {
    color: '#FF5A5A',
    fontSize: 12,
    fontWeight: 'bold',
  },

  // Home Content Container
  homeContentContainer: {
    paddingHorizontal: 20,
  },

  // Welcome Section
  welcomeSection: {
    paddingTop: 24,
    paddingBottom: 10,
    paddingLeft: 18,
    paddingRight: 18,
  },
  welcomeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  welcomeIcon: {
    marginRight: 8,
  },
  welcomeText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  familyNameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
    paddingVertical: 4,
  },
  chatContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
  },
  familyNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 8,
  },
  familySelectorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: width * 0.45,
  },
  familyLogoBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 182, 193, 0.5)',
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  familyTextColumn: {
    flex: 1,
  },
  familyLabelText: {
    fontSize: 11,
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  chatCycleCard: {
    // plain touchable like notification icon
    padding: 0,
    borderRadius: 20,
    marginRight: 4,
  },
  chatBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FF6B6B',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
  },
  chatBadgeText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  familyAvatarContainer: {
    // no longer used for chat
  },
  rotatingAvatar: {
    // removed background avatar
  },
  messageBadge: {
  },
  messageBadgeText: {
  },
  notificationIconContainer: {
    // inline in row, to the left of chat
    marginRight: 4,
    marginTop: 0,
    paddingRight: 8,
    zIndex: 10,
  },
  notificationIcon: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationBadgeSmall: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
  },
  notificationBadgeSmallText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  familyNameText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  settingsButton: {
    padding: 8,
    borderRadius: 9999,
    backgroundColor: 'rgba(255, 182, 193, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 182, 193, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },

  // Placeholder Card
  placeholderCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFD700',
    borderStyle: 'dashed',
  },
  placeholderText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333333',
    marginTop: 16,
    marginBottom: 8,
  },
  placeholderSubtext: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
  },

  // Empty State Styles
  emptyStateContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderStyle: 'dashed',
  },
  emptyStateMessageContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyStateMessage: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 20,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    lineHeight: 20,
  },

  // Emergency Section
  emergencySection: {
    paddingVertical: 20,
    paddingHorizontal: 4,
  },
  emergencyButton: {
    backgroundColor: '#EF4444',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#EF4444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  emergencyButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },

  // Main Content Card (Background for tabs and content) - White with More Rounded Top
  mainContentCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    marginHorizontal: 0,
    marginTop: 8, // Default margin, animation will handle positioning
    marginBottom: 0,
    paddingVertical: 16,
    paddingHorizontal: 0,
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255, 182, 193, 0.2)',
    shadowColor: '#FFB6C1',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },

  // Content Card Header
  contentCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  contentCardHeaderLeft: {
    flex: 1,
  },
  contentCardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333333',
  },
  contentCardHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Main ScrollView
  mainScrollView: {
    flex: 1,
  },
  mainScrollContent: {
    flexGrow: 1,
    minHeight: '100%',
  },

  // Card Internal ScrollView
  cardScrollView: {
    flex: 1,
  },
  cardScrollContent: {
    paddingBottom: 20,
  },

  // Widget Container (Original Design)
  widgetContainer: {
    background: 'linear-gradient(135deg, #FFFFFF 0%, #FAFAFA 100%)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FFD700',
    shadowColor: '#D32F2F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 32,
    elevation: 8,
    padding: 20,
    margin: 12,
  },

  // Widget Header (Original Design)
  widgetHeader: {
    color: '#D32F2F',
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },

  // Section Styles
  section: {
    marginBottom: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#D32F2F',
    paddingHorizontal: 20,
  },
  addAppointmentButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEF7F7',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFB6C1',
    marginRight: 10,
  },

  // Calendar Drawer Styles
  calendarDrawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  calendarDrawerContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
    minHeight: '60%',
  },
  calendarDrawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  calendarDrawerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#374151',
  },
  calendarDrawerContent: {
    flex: 1,
    padding: 20,
  },
  calendarInputGroup: {
    marginBottom: 20,
  },
  calendarInputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  calendarInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#374151',
    backgroundColor: '#FFFFFF',
  },
  calendarTextArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  calendarDrawerFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  calendarShareButtons: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  calendarShareButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    gap: 8,
  },
  calendarShareButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  calendarCreateButton: {
    backgroundColor: '#FFB6C1',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  calendarCreateButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },

  // hourse Members Section
  familyMembersScrollView: {
    paddingHorizontal: 4,
  },
  familyMembersSection: {
    paddingHorizontal: 8,
    marginHorizontal: 8,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },

  // Group Avatar
  groupAvatarCard: {
    width: 70,
    height: 70,
    backgroundColor: '#FFFFFF',
    borderRadius: 35,
    paddingVertical: 4,
    paddingHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Individual Members
  individualMembersCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
  },
  individualMembersScroll: {
    paddingHorizontal: 0,
  },
  memberContainer: {
    marginRight: 4,
    alignItems: 'center',
  },
  memberAvatar: {
    position: 'relative',
    borderRadius: 30,
    overflow: 'hidden',
    zIndex: 1,
  },
  compositeAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#007AFF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 1,
  },
  avatarGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  avatarQuarter: {
    width: '50%',
    height: '50%',
    backgroundColor: '#DDD',
  },
  avatarTopLeft: { backgroundColor: '#FFB7B7' },
  avatarTopRight: { backgroundColor: '#FF8C8C' },
  avatarBottomLeft: { backgroundColor: '#FF5A5A' },
  avatarBottomRight: { backgroundColor: '#FFB7B7' },
  singleAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
    zIndex: 1,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  memberBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FF5A5A',
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  memberBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 16,
  },
  moreMembers: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Tabs Container
  tabsContainer: {
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 28,
    gap: 8,
    backgroundColor: 'transparent',
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tab: {
    width: 120,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 9999,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 182, 193, 0.1)',
    borderWidth: 0,
    borderColor: 'transparent',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  activeTab: {
    backgroundColor: '#FFB6C1',
    borderColor: '#FF69B4',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  activeTabGradient: {
    width: 120,
    borderRadius: 9999,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  activeTabTouchable: {
    width: 120,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 9999,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
  },
  activeTabCard: {
    alignSelf: 'center',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    overflow: 'hidden',
  },
  activeTabCardGradient: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    minWidth: 120,
    justifyContent: 'center',
  },
  activeTabCardText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  tabText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    textAlign: 'center',
  },
  activeTabText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },

  // Asset cards scrollable container
  assetCardsScroll: {
    marginVertical: 16,
  },
  assetCardsContainer: {
    paddingHorizontal: 20,
    gap: 16,
    flexDirection: 'column',
  },
  assetCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  assetCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  assetCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
  },
  assetCardValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  assetCardProgress: {
    height: 6,
    backgroundColor: '#E5E7EB',
    borderRadius: 3,
    marginBottom: 8,
  },
  assetCardProgressBar: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: 3,
  },
  assetCardChange: {
    fontSize: 14,
    color: '#10B981',
    fontWeight: '500',
  },
  // Portfolio styles
  portfolioContainer: {
    gap: 12,
    paddingHorizontal: 20,
  },
  portfolioItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  portfolioItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  portfolioIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  portfolioIconText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  portfolioItemInfo: {
    flex: 1,
  },
  portfolioItemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 2,
  },
  portfolioItemValue: {
    fontSize: 14,
    color: '#6B7280',
  },
  portfolioItemChange: {
    fontSize: 14,
    color: '#10B981',
    fontWeight: '600',
  },
  // Asset card styles
  assetCard: {
    width: 280,
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  assetCardContainer: {
    position: 'relative',
    width: '100%',
    height: '100%',
  },
  assetProgressBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
    overflow: 'hidden',
    zIndex: 1,
  },
  assetProgressFill: {
    height: '100%',
    borderRadius: 16,
  },
  assetGradient: {
    padding: 24,
    zIndex: 2,
  },
  assetContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  assetLeft: {
    marginRight: 16,
  },
  coinIcon: {
    position: 'relative',
    width: 60,
    minHeight: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sparkle1: {
    position: 'absolute',
    top: -5,
    right: -5,
  },
  sparkle2: {
    position: 'absolute',
    bottom: -3,
    left: -3,
  },
  assetRight: {
    flex: 1,
  },
  assetLabel: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 4,
  },
  assetValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  assetTarget: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },

  // Attention Applications styles
  attentionApplicationsContainer: {
    gap: 12,
  },
  attentionApplicationsList: {
    gap: 8,
  },
  attentionAppItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(224, 224, 224, 0.5)',
    marginBottom: 6,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  attentionAppHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  attentionAppIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  attentionAppInfo: {
    flex: 1,
  },
  attentionAppName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 3,
  },
  dueDateInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dueDateText: {
    fontSize: 12,
    color: '#666666',
  },
  daysLeftText: {
    fontSize: 12,
    fontWeight: '600',
  },
  appNotificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#FF5A5A',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  appNotificationText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },

  // Circular Add Wallet Button Styles
  circularAddWalletButton: {
    width: 280,
    height: 120,
    borderRadius: 16,
    backgroundColor: '#F8F9FA',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  circularAddWalletIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4F46E5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  circularAddWalletText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666666',
  },

  // Social Posts Styles
  socialPostsContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  socialPostCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  postHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  postAuthor: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  postAuthorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  postAuthorInfo: {
    flex: 1,
  },
  postAuthorNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  postAuthorName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  postTimestamp: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  postMoreButton: {
    padding: 4,
  },
  postContent: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
    marginBottom: 12,
  },
  postMedia: {
    marginBottom: 12,
  },
  postImage: {
    width: '100%',
    height: 200,
    borderRadius: 8,
  },
  postVideo: {
    width: '100%',
    height: 200,
    borderRadius: 8,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  postLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  postLocationText: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 4,
  },
  postTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  postTag: {
    fontSize: 12,
    color: '#4F46E5',
    marginRight: 8,
    marginBottom: 4,
  },
  postActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  postAction: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  postActionText: {
    fontSize: 14,
    color: '#6B7280',
    marginLeft: 4,
  },

  // hourse Status Cards Styles (Legacy - keeping for compatibility)
  familyStatusCardsContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  emergencyStatusCard: {
    borderWidth: 2,
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  statusCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  statusCardMember: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  statusCardAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
  },
  statusCardMemberInfo: {
    flex: 1,
  },
  statusCardMemberName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
  },
  statusCardStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  statusCardStatus: {
    fontSize: 12,
    color: '#6B7280',
    textTransform: 'capitalize',
  },
  statusCardContent: {
    gap: 8,
  },
  statusCardInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusCardInfoText: {
    fontSize: 14,
    color: '#6B7280',
    marginLeft: 8,
  },
  heartRateChart: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  heartRateChartTitle: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
  },
  heartRateChartContainer: {
    height: 40,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    justifyContent: 'center',
  },
  heartRateChartLine: {
    height: 2,
    backgroundColor: '#EF4444',
    marginHorizontal: 8,
    borderRadius: 1,
  },

  // Modal Styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    margin: 20,
    maxHeight: '80%',
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
  },
  modalCloseButton: {
    padding: 4,
  },
  modalContent: {
    maxHeight: 400,
    padding: 20,
  },
  modalSection: {
    marginBottom: 20,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  modalDescription: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 20,
  },
  modalTextInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#374151',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  modalCancelButton: {
    flex: 1,
    padding: 12,
    marginRight: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 182, 193, 0.2)',
    backgroundColor: 'rgba(255, 182, 193, 0.1)',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  modalCancelText: {
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '500',
  },
  modalPostButton: {
    flex: 1,
    padding: 12,
    marginLeft: 8,
    borderRadius: 8,
    backgroundColor: '#FFB6C1',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  modalPostText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  modalSaveButton: {
    flex: 1,
    padding: 12,
    marginLeft: 8,
    borderRadius: 8,
    backgroundColor: '#10B981',
    alignItems: 'center',
  },
  modalSaveText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '500',
  },

  // Tag Styles
  tagInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  tagInput: {
    flex: 1,
    padding: 12,
    fontSize: 16,
    color: '#374151',
  },
  addTagButton: {
    padding: 8,
    marginRight: 4,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E0E7FF',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  tagChipText: {
    fontSize: 12,
    color: '#4F46E5',
    marginRight: 4,
  },

  // Report Modal Styles
  reportOptionsContainer: {
    gap: 8,
  },
  reportOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
  },
  reportOptionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  reportOptionContent: {
    flex: 1,
  },
  reportOptionTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1F2937',
    marginBottom: 4,
  },
  reportOptionDescription: {
    fontSize: 14,
    color: '#6B7280',
  },

  // Add Wallet Modal Styles
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  iconOption: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  iconOptionActive: {
    backgroundColor: '#4F46E5',
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  colorOption: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorOptionActive: {
    borderColor: '#1F2937',
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  toggleLabel: {
    fontSize: 16,
    color: '#374151',
  },
  toggle: {
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#D1D5DB',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  toggleActive: {
    backgroundColor: '#4F46E5',
  },
  toggleThumb: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  toggleThumbActive: {
    transform: [{ translateX: 20 }],
  },

  // Original Component Styles (Legacy - keeping for compatibility)
  // hourse Member Styles
  memberContainer: {
    alignItems: 'center',
    marginRight: 16,
  },
  memberAvatar: {
    position: 'relative',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  compositeAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#E0E0E0',
    overflow: 'hidden',
  },
  avatarGrid: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  avatarQuarter: {
    width: '50%',
    height: '50%',
    backgroundColor: '#C0C0C0',
  },
  avatarTopLeft: {
    borderTopLeftRadius: 30,
  },
  avatarTopRight: {
    borderTopRightRadius: 30,
  },
  avatarBottomLeft: {
    borderBottomLeftRadius: 30,
  },
  avatarBottomRight: {
    borderBottomRightRadius: 30,
  },
  singleAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImageContainer: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarContent: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  // Custom Avatar Parts
  avatarHair: {
    position: 'absolute',
    top: 5,
    left: 10,
    width: 40,
    height: 20,
    backgroundColor: '#FFD700',
    borderRadius: 10,
  },
  avatarSunglasses: {
    position: 'absolute',
    top: 15,
    left: 15,
    width: 30,
    height: 8,
    backgroundColor: '#000000',
    borderRadius: 4,
  },
  avatarVest: {
    position: 'absolute',
    top: 25,
    left: 20,
    width: 20,
    height: 25,
    backgroundColor: '#8B4513',
    borderRadius: 2,
  },
  avatarCup: {
    position: 'absolute',
    top: 30,
    right: 10,
    width: 8,
    height: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
  },
  avatarCane: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    width: 3,
    height: 20,
    backgroundColor: '#8B4513',
    borderRadius: 1,
  },
  avatarTurban: {
    position: 'absolute',
    top: 5,
    left: 10,
    width: 40,
    height: 15,
    backgroundColor: '#FF6B35',
    borderRadius: 8,
  },
  avatarBeard: {
    position: 'absolute',
    top: 20,
    left: 20,
    width: 20,
    height: 15,
    backgroundColor: '#8B4513',
    borderRadius: 10,
  },
  avatarSuit: {
    position: 'absolute',
    top: 25,
    left: 15,
    width: 30,
    height: 30,
    backgroundColor: '#000000',
    borderRadius: 2,
  },
  avatarTie: {
    position: 'absolute',
    top: 30,
    left: 25,
    width: 10,
    height: 20,
    backgroundColor: '#FF0000',
    borderRadius: 1,
  },
  avatarPhone: {
    position: 'absolute',
    top: 35,
    right: 10,
    width: 6,
    height: 12,
    backgroundColor: '#000000',
    borderRadius: 3,
  },
  avatarCurlyHair: {
    position: 'absolute',
    top: 5,
    left: 10,
    width: 40,
    height: 20,
    backgroundColor: '#8B4513',
    borderRadius: 15,
  },
  avatarGreenTop: {
    position: 'absolute',
    top: 25,
    left: 15,
    width: 30,
    height: 30,
    backgroundColor: '#00FF00',
    borderRadius: 5,
  },
  avatarNecklace: {
    position: 'absolute',
    top: 30,
    left: 20,
    width: 20,
    height: 3,
    backgroundColor: '#FFD700',
    borderRadius: 1,
  },
  avatarVitiligo: {
    position: 'absolute',
    top: 15,
    right: 15,
    width: 8,
    height: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
  },
  memberBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#FF5A5A',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  memberBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },

  // hourse Status Card Styles (Legacy - keeping for compatibility)
  familyStatusBackgroundChart: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.3,
  },
  familyStatusGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  familyStatusContent: {
    position: 'relative',
    zIndex: 1,
  },
  familyStatusTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  familyStatusInfo: {
    flex: 1,
  },
  familyStatusStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  familyStatusStatusText: {
    fontSize: 10,
    fontWeight: '600',
  },
  familyStatusBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  familyStatusMetricIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 90, 90, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  areaChartContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  areaChartBackground: {
    position: 'relative',
    width: '100%',
    height: '100%',
  },
  areaChartFill: {
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  areaChartLine: {
    position: 'absolute',
    bottom: 0,
    left: 0,
  },

  // Social Post Styles (Legacy - keeping for compatibility)
  socialPost: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  postAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  postUserInfo: {
    flex: 1,
  },
  postUserName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 2,
  },
  postTimeAgo: {
    fontSize: 12,
    color: '#6B7280',
  },
  postMenuButton: {
    padding: 4,
  },
  reportDropdown: {
    position: 'absolute',
    top: 40,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 10,
  },
  reportOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  reportOptionText: {
    fontSize: 14,
    color: '#FF5A5A',
    marginLeft: 8,
  },
  postContent: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
    marginBottom: 12,
  },
  postMedia: {
    marginBottom: 12,
  },
  postImage: {
    width: '100%',
    height: 200,
    borderRadius: 8,
  },
  postActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  actionText: {
    fontSize: 14,
    color: '#6B7280',
    marginLeft: 4,
  },
  socialPostSeparator: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginBottom: 16,
  },

  // hourse Members Container (Legacy - keeping for compatibility)
  familyMembersContainer: {
    marginBottom: 16,
  },

  // Widget Styles (Legacy - keeping for compatibility)
  widgetContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  widgetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  widgetTitleContainer: {
    flex: 1,
  },
  widgetTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 2,
  },
  widgetSubtitle: {
    fontSize: 12,
    color: '#6B7280',
  },
  addButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  widgetScrollContent: {
    paddingRight: 16,
  },

  // Appointment styles moved to styles/home/appointments.ts (Legacy - keeping for compatibility)
  appointmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  appointmentAttendees: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appointmentAttendeesText: {
    fontSize: 12,
    color: '#4F46E5',
    fontWeight: '500',
  },

  // Shopping List Styles (Legacy - keeping for compatibility)
  shoppingItemCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    marginRight: 12,
    width: 180,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  shoppingItemCompleted: {
    opacity: 0.6,
  },
  shoppingItemHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  shoppingItemCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFB6C1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shoppingItemCheckboxCompleted: {
    backgroundColor: '#FFB6C1',
    borderColor: '#FF6B6B',
  },
  shoppingItemInfo: {
    flex: 1,
  },
  shoppingItemName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    flex: 1,
    textAlign: 'center',
  },
  shoppingItemNameCompleted: {
    textDecorationLine: 'line-through',
    color: '#9CA3AF',
  },
  shoppingItemQuantity: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  shoppingItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shoppingItemCategory: {
    fontSize: 12,
    color: '#4F46E5',
    fontWeight: '500',
  },
  shoppingItemAssignee: {
    fontSize: 12,
    color: '#6B7280',
  },

  // Recently Used Styles (Legacy - keeping for compatibility)
  recentAppCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    marginRight: 12,
    width: 100,
    alignItems: 'center',
  },
  recentAppIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#EEF2FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  recentAppName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1F2937',
    textAlign: 'center',
    marginBottom: 4,
  },
  recentAppLastUsed: {
    fontSize: 10,
    color: '#6B7280',
    textAlign: 'center',
  },

  // Quick Actions Styles (Legacy - keeping for compatibility)
  quickActionsContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  quickActionsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 16,
  },
  quickActionButton: {
    flex: 1,
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  quickActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4F46E5',
    marginTop: 8,
    textAlign: 'center',
  },

  // Location Map Widget Styles (Legacy - keeping for compatibility)
  locationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  locationIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationStatus: {
    position: 'relative',
  },
  locationFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  locationDistance: {
    fontSize: 12,
    color: '#4F46E5',
    fontWeight: '500',
  },
  locationLastSeen: {
    fontSize: 10,
    color: '#9CA3AF',
  },
  batteryIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  batteryText: {
    fontSize: 10,
    color: '#6B7280',
    marginLeft: 4,
  },
  widgetActions: {
    flexDirection: 'row',
    gap: 8,
  },

  // Widget Customization Styles (Legacy - keeping for compatibility)
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  categoryTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937'
  },

  // Additional styles for original HomeScreen components (Legacy - keeping for compatibility)
  shoppingItem: {
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shoppingItemText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1F2937',
  },
  widgetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    marginBottom: 8,
  },
  widgetOptionActive: {
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#4F46E5',
  },
  widgetOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  widgetOptionName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1F2937',
    marginLeft: 12,
  },

  // Create hourse Modal Styles (Legacy - keeping for compatibility)
  familyTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  familyTypeOption: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  familyTypeOptionActive: {
    backgroundColor: '#4F46E5',
    borderColor: '#4F46E5',
  },
  familyTypeText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#4F46E5',
    marginTop: 8,
    textAlign: 'center',
  },
  familyTypeTextActive: {
    color: '#FFFFFF',
  },

  // Toggle Styles
  toggle: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#D1D5DB',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  toggleActive: {
    backgroundColor: '#4F46E5',
  },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  toggleThumbActive: {
    transform: [{ translateX: 20 }],
  },

  // Header Button Styles
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
  },

  // Attention styles moved to styles/home/attention.ts

  // Shopping styles moved to styles/home/shopping.ts

  // Map Styles
  mapContainer: {
    height: 200,
    backgroundColor: '#F5F5F5',
    marginTop: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  mapPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPlaceholderText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginTop: 8,
  },
  mapPlaceholderSubtext: {
    fontSize: 12,
    color: '#666666',
    marginTop: 4,
  },
  familyAvatarsOnMap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  familyAvatarOnMap: {
    position: 'absolute',
    alignItems: 'center',
  },
  familyAvatarCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#D32F2F',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  familyAvatarText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  familyAvatarName: {
    fontSize: 10,
    color: '#333333',
    marginTop: 2,
    textAlign: 'center',
  },

  // Floating Create Post Button
  floatingCreatePostButton: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#D32F2F',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },

  // Social Post List Styles
  socialPostListItem: {
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  socialPostHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  socialPostAuthor: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  socialPostAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFB6C1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  socialPostAvatarText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  socialPostAuthorInfo: {
    flex: 1,
  },
  socialPostAuthorNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  socialPostAuthorName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
  },
  socialPostTimestamp: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  socialPostMoreButton: {
    padding: 4,
  },
  socialPostContent: {
    fontSize: 15,
    color: '#374151',
    lineHeight: 20,
    marginBottom: 12,
  },
  socialPostMedia: {
    marginBottom: 12,
  },
  socialPostMediaPlaceholder: {
    height: 200,
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  socialPostMediaText: {
    fontSize: 14,
    color: '#9CA3AF',
    marginTop: 8,
  },
  socialPostActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 24,
  },
  socialPostAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  socialPostActionText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  socialPostDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginTop: 16,
  },

  // Comment Drawer Styles
  commentDrawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  commentDrawer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
    minHeight: '60%',
  },
  commentDrawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  commentDrawerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
  },
  commentDrawerCloseButton: {
    padding: 4,
  },
  commentList: {
    flex: 1,
    paddingHorizontal: 20,
  },
  commentItem: {
    flexDirection: 'row',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFB6C1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  commentAvatarText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  commentContent: {
    flex: 1,
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  commentAuthorName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginRight: 8,
  },
  commentTimestamp: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  commentText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 18,
  },
  
  // Inline Links in Comments
  commentInlineLink: {
    color: '#3B82F6',
    textDecorationLine: 'underline',
    fontWeight: '500',
  },
  
  // Comment Image Preview
  commentImageContainer: {
    marginTop: 8,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  commentImage: {
    width: 200,
    height: 150,
    borderRadius: 8,
  },
  
  // Comment Attachments
  commentAttachment: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  commentAttachmentPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  commentAttachmentInfo: {
    marginLeft: 8,
  },
  commentAttachmentText: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '500',
  },
  commentAttachmentSize: {
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 2,
  },
  commentAttachmentButton: {
    padding: 4,
    marginLeft: 8,
  },
  
  addCommentSection: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  addCommentInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  addCommentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: '#374151',
    backgroundColor: '#FFFFFF',
    maxHeight: 100,
  },
  attachmentButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  addCommentButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFB6C1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  
  // Attachment Preview Styles
  attachmentPreview: {
    marginBottom: 12,
  },
  attachmentPreviewItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#F0F9FF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0F2FE',
  },
  attachmentPreviewImage: {
    width: 30,
    height: 30,
    borderRadius: 4,
  },
  attachmentPreviewText: {
    fontSize: 13,
    color: '#3B82F6',
    marginLeft: 8,
    flex: 1,
  },
  attachmentRemoveButton: {
    padding: 4,
    marginLeft: 8,
  },

  // Create Post Modal
  createPostModal: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 16,
    padding: 24,
    margin: 24,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: 'rgba(255, 182, 193, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  postInput: {
    borderWidth: 1,
    borderColor: 'rgba(255, 182, 193, 0.2)',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#374151',
    textAlignVertical: 'top',
    minHeight: 100,
    marginBottom: 16,
    backgroundColor: 'rgba(255, 182, 193, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },

  // Goals styles moved to styles/home/goals.ts

  // hourse Dropdown Styles
  familyDropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  familyDropdownContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    margin: 20,
    maxHeight: '70%',
    minWidth: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  familyDropdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  familyDropdownTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
  },
  familyDropdownList: {
    maxHeight: 300,
  },
  familyDropdownItem: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  familyDropdownItemSelected: {
    backgroundColor: '#FEF7F7',
  },
  familyDropdownItemContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  familyDropdownItemLogo: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF8DC',
    borderWidth: 2,
    borderColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  familyDropdownItemInfo: {
    flex: 1,
  },
  familyDropdownItemName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 2,
  },
  familyDropdownItemNameSelected: {
    color: '#FFB6C1',
    fontWeight: '600',
  },
  familyDropdownItemMembers: {
    fontSize: 14,
    color: '#6B7280',
  },

  // New hourse Tab Redesign Styles
  
  // hourse Overview Header
  familyOverviewHeader: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  familyOverviewStats: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  familyStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  familyStatNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  familyStatLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  familyStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 16,
  },

  // Section Headers
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  sectionActionButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
  },
  addMemberButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFB6C1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  refreshButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    marginRight: 8, // Add margin to move button away from right edge
  },
  mapToggleButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    marginRight: 8, // Add margin to move button away from right edge
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  viewAllButtonText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  insightsButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
  },

  // Quick Actions
  quickActionsGrid: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 4,
  },
  quickActionCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  quickActionCardActive: {
    borderColor: '#FFB6C1',
    backgroundColor: '#FEF7F7',
  },
  quickActionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickActionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#374151',
    textAlign: 'center',
  },

  // Enhanced hourse Members
  familyMembersScrollContent: {
    paddingVertical: 8,
  },
  familyMemberCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginRight: 12,
    width: 120,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  familyMemberCardSelected: {
    borderColor: '#FFB6C1',
    backgroundColor: '#FEF7F7',
  },
  familyMemberCardContent: {
    padding: 12,
    alignItems: 'center',
  },
  familyMemberAvatarContainer: {
    position: 'relative',
    marginBottom: 8,
  },
  familyMemberAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  familyMemberAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
    overflow: 'hidden',
  },
  familyMemberAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  familyMemberStatusIndicator: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  familyMemberNotificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  familyMemberNotificationText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  familyMemberInfo: {
    alignItems: 'center',
    flex: 1,
  },
  familyMemberName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
    textAlign: 'center',
  },
  familyMemberDetails: {
    alignItems: 'center',
  },
  familyMemberRole: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 2,
  },
  familyMemberRoleText: {
    fontSize: 10,
    color: '#6B7280',
  },
  familyMemberLastSeen: {
    fontSize: 10,
    color: '#9CA3AF',
  },
  familyMemberQuickActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  familyMemberActionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addFamilyMemberCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    marginRight: 12,
    width: 120,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
  },
  addFamilyMemberIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  addFamilyMemberText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
    textAlign: 'center',
  },

  // Enhanced hourse Status Cards
  familyStatusScrollContent: {
    paddingVertical: 12,
  },
  familyStatusVerticalContainer: {
    gap: 12,
  },
  familyStatusCard: {
    backgroundColor: 'transparent',
    borderRadius: 20,
    marginRight: 0,
    marginLeft: 20,
    marginRight: 20,
    width: 'auto',
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  familyStatusCardGradient: {
    borderRadius: 20,
    padding: 0,
    backgroundColor: 'transparent',
  },
  familyStatusCardEmergency: {
    borderWidth: 2,
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
    shadowColor: '#EF4444',
    shadowOpacity: 0.3,
  },
  familyStatusCardExpanded: {
    width: 'auto',
  },
  familyStatusCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
  },
  familyStatusAvatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  familyStatusAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
  },
  familyStatusAvatarText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  familyStatusIndicator: {
    position: 'absolute',
    bottom: 1,
    right: 1,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 0,
  },
  familyStatusHeaderInfo: {
    flex: 1,
    marginLeft: 12,
  },
  familyStatusName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 2,
  },
  familyStatusTime: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  familyStatusLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  familyStatusStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  familyStatusStatItem: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
  },
  familyStatusStatIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  familyStatusStatValue: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1F2937',
  },
  emergencyIndicator: {
    padding: 4,
    borderRadius: 12,
    backgroundColor: '#FEE2E2',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  familyStatusLocation: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 4,
    flex: 1,
    fontWeight: '500',
  },
  familyStatusExpandedContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    marginTop: 8,
    backgroundColor: '#FFFFFF',
  },
  familyStatusAdditionalMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  familyStatusAdditionalMetric: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F9FAFB',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  familyStatusAdditionalMetricText: {
    fontSize: 10,
    color: '#6B7280',
  },
  familyStatusActivity: {
    marginBottom: 12,
  },
  familyStatusActivityLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 4,
  },
  familyStatusActivityText: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '500',
  },
  familyStatusQuickActions: {
    flexDirection: 'row',
    gap: 8,
  },
  familyStatusActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#F3F4F6',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  familyStatusActionText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },

  // Enhanced hourse Location Map
  familyLocationCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  familyLocationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  familyLocationHeaderLeft: {
    flex: 1,
  },
  familyLocationTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
  },
  familyLocationStats: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  familyLocationStatsText: {
    fontSize: 12,
    color: '#6B7280',
  },
  familyLocationHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  familyLocationViewToggle: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    padding: 2,
  },
  familyLocationToggleButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  familyLocationToggleButtonActive: {
    backgroundColor: '#FFB6C1',
  },
  familyLocationRefreshButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
  },
  familyLocationMap: {
    height: 300,
    overflow: 'hidden',
  },
  familyLocationMapContainer: {
    flex: 1,
    position: 'relative',
  },
  familyLocationMapPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
  },
  familyLocationMapText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 8,
  },
  familyLocationMapSubtext: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
    textAlign: 'center',
  },
  familyLocationMapPins: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  familyLocationMapPin: {
    position: 'absolute',
    alignItems: 'center',
  },
  familyLocationMapPinAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  familyLocationMapPinText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  familyLocationMapPinPulse: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(16, 185, 129, 0.3)',
    top: 0,
    left: 0,
  },
  familyLocationList: {
    maxHeight: 300,
  },
  familyLocationItem: {
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  familyLocationItemSelected: {
    backgroundColor: '#FEF7F7',
  },
  familyLocationItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  familyLocationItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  familyLocationItemAvatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  familyLocationItemAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  familyLocationItemAvatarText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  familyLocationItemOnlineIndicator: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  familyLocationItemInfo: {
    flex: 1,
  },
  familyLocationItemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 2,
  },
  familyLocationItemAddress: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 2,
  },
  familyLocationItemTime: {
    fontSize: 10,
    color: '#9CA3AF',
  },
  familyLocationItemRight: {
    alignItems: 'flex-end',
    gap: 8,
  },
  familyLocationItemBattery: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  familyLocationItemBatteryText: {
    fontSize: 10,
    color: '#6B7280',
  },
  familyLocationItemActions: {
    flexDirection: 'row',
    gap: 8,
  },
  familyLocationItemActionButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  familyLocationItemExpanded: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: '#F9FAFB',
  },
  familyLocationItemDetails: {
    gap: 8,
  },
  familyLocationItemDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  familyLocationItemDetailText: {
    fontSize: 12,
    color: '#6B7280',
  },
  familyLocationQuickActions: {
    flexDirection: 'row',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    gap: 16,
  },
  familyLocationQuickAction: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#F3F4F6',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  familyLocationQuickActionText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },

  // Recent Activities
  recentActivitiesList: {
    gap: 8,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
  },
  activityIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  activityContent: {
    flex: 1,
  },
  activityText: {
    fontSize: 14,
    color: '#374151',
    marginBottom: 2,
  },
  activityUser: {
    fontWeight: '600',
    color: '#1F2937',
  },
  activityTime: {
    fontSize: 12,
    color: '#9CA3AF',
  },

  // hourse Insights
  insightsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingHorizontal: 20,
  },
  insightCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  insightIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  insightValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  insightLabel: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
  },

  // Shopping Drawer Styles
  shoppingDrawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  shoppingDrawerContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    minHeight: '70%',
  },
  shoppingDrawerHeader: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  shoppingDrawerHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  shoppingDrawerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  shoppingDrawerIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  shoppingDrawerTitleContainer: {
    flex: 1,
  },
  shoppingDrawerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  shoppingDrawerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  shoppingDrawerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shoppingDrawerContent: {
    flex: 1,
    padding: 20,
  },
  shoppingDrawerField: {
    marginBottom: 20,
  },
  shoppingDrawerFieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  shoppingDrawerInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1F2937',
    backgroundColor: '#FFFFFF',
  },
  shoppingDrawerCategoryScroll: {
    marginTop: 8,
  },
  shoppingDrawerCategoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  shoppingDrawerCategoryItemSelected: {
    backgroundColor: '#FFB6C1',
    borderColor: '#FF69B4',
  },
  shoppingDrawerCategoryText: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 6,
    fontWeight: '500',
  },
  shoppingDrawerCategoryTextSelected: {
    color: '#FFFFFF',
  },
  shoppingDrawerLocationScroll: {
    marginTop: 8,
  },
  shoppingDrawerLocationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  shoppingDrawerLocationItemSelected: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
  },
  shoppingDrawerLocationText: {
    fontSize: 11,
    color: '#6B7280',
    marginLeft: 4,
    fontWeight: '500',
  },
  shoppingDrawerLocationTextSelected: {
    color: '#FFFFFF',
  },
  shoppingDrawerDateScroll: {
    marginTop: 8,
  },
  shoppingDrawerDateItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  shoppingDrawerDateItemSelected: {
    backgroundColor: '#3B82F6',
    borderColor: '#2563EB',
  },
  shoppingDrawerDateText: {
    fontSize: 11,
    color: '#6B7280',
    marginLeft: 4,
    fontWeight: '500',
  },
  shoppingDrawerDateTextSelected: {
    color: '#FFFFFF',
  },
  shoppingDrawerAssigneeScroll: {
    marginTop: 8,
  },
  shoppingDrawerAssigneeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  shoppingDrawerAssigneeItemSelected: {
    backgroundColor: '#8B5CF6',
    borderColor: '#7C3AED',
  },
  shoppingDrawerAssigneeText: {
    fontSize: 11,
    color: '#6B7280',
    marginLeft: 4,
    fontWeight: '500',
  },
  shoppingDrawerAssigneeTextSelected: {
    color: '#FFFFFF',
  },
  shoppingDrawerAddButton: {
    marginTop: 20,
    borderRadius: 12,
    overflow: 'hidden',
  },
  shoppingDrawerAddButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  shoppingDrawerAddButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },

  // Enhanced Shopping Drawer Styles
  shoppingDrawerSearchContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
  },
  shoppingDrawerSearchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1F2937',
    backgroundColor: '#FFFFFF',
    paddingRight: 40,
  },
  shoppingDrawerSearchLoader: {
    position: 'absolute',
    right: 12,
  },
  shoppingDrawerSearchResults: {
    marginTop: 8,
    maxHeight: 200,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  shoppingDrawerSearchResultsScroll: {
    maxHeight: 200,
  },
  shoppingDrawerSearchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  shoppingDrawerSearchResultItemSelected: {
    backgroundColor: '#F0F9FF',
  },
  shoppingDrawerSearchResultContent: {
    flex: 1,
    marginLeft: 12,
  },
  shoppingDrawerSearchResultTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1F2937',
    marginBottom: 2,
  },
  shoppingDrawerSearchResultSubtitle: {
    fontSize: 12,
    color: '#6B7280',
  },
  shoppingDrawerCategoryGrid: {
    marginTop: 8,
  },
  shoppingDrawerCategoryGridItem: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    margin: 4,
    borderRadius: 12,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  shoppingDrawerCategoryGridItemSelected: {
    backgroundColor: '#F0F9FF',
    borderColor: '#3B82F6',
  },
  shoppingDrawerCategoryGridIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  shoppingDrawerCategoryGridText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#374151',
    textAlign: 'center',
  },
  shoppingDrawerCategoryGridTextSelected: {
    color: '#1D4ED8',
  },
  shoppingDrawerMemberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shoppingDrawerMemberAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  shoppingDrawerMemberOnlineIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
}); // End of styles

