
import { Pool } from 'pg';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : undefined
});

const countries = [
    { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', phone_code: '+93' },
    { code: 'AL', name: 'Albania', flag: '🇦🇱', phone_code: '+355' },
    { code: 'DZ', name: 'Algeria', flag: '🇩🇿', phone_code: '+213' },
    { code: 'AS', name: 'American Samoa', flag: '🇦🇸', phone_code: '+1-684' },
    { code: 'AD', name: 'Andorra', flag: '🇦🇩', phone_code: '+376' },
    { code: 'AO', name: 'Angola', flag: '🇦🇴', phone_code: '+244' },
    { code: 'AI', name: 'Anguilla', flag: '🇦🇮', phone_code: '+1-264' },
    { code: 'AQ', name: 'Antarctica', flag: '🇦🇶', phone_code: '+672' },
    { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', phone_code: '+1-268' },
    { code: 'AR', name: 'Argentina', flag: '🇦🇷', phone_code: '+54' },
    { code: 'AM', name: 'Armenia', flag: '🇦🇲', phone_code: '+374' },
    { code: 'AW', name: 'Aruba', flag: '🇦🇼', phone_code: '+297' },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', phone_code: '+61' },
    { code: 'AT', name: 'Austria', flag: '🇦🇹', phone_code: '+43' },
    { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', phone_code: '+994' },
    { code: 'BS', name: 'Bahamas', flag: '🇧🇸', phone_code: '+1-242' },
    { code: 'BH', name: 'Bahrain', flag: '🇧🇭', phone_code: '+973' },
    { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', phone_code: '+880' },
    { code: 'BB', name: 'Barbados', flag: '🇧🇧', phone_code: '+1-246' },
    { code: 'BY', name: 'Belarus', flag: '🇧🇾', phone_code: '+375' },
    { code: 'BE', name: 'Belgium', flag: '🇧🇪', phone_code: '+32' },
    { code: 'BZ', name: 'Belize', flag: '🇧🇿', phone_code: '+501' },
    { code: 'BJ', name: 'Benin', flag: '🇧🇯', phone_code: '+229' },
    { code: 'BM', name: 'Bermuda', flag: '🇧🇲', phone_code: '+1-441' },
    { code: 'BT', name: 'Bhutan', flag: '🇧🇹', phone_code: '+975' },
    { code: 'BO', name: 'Bolivia', flag: '🇧🇴', phone_code: '+591' },
    { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', phone_code: '+387' },
    { code: 'BW', name: 'Botswana', flag: '🇧🇼', phone_code: '+267' },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷', phone_code: '+55' },
    { code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴', phone_code: '+246' },
    { code: 'VG', name: 'British Virgin Islands', flag: '🇻🇬', phone_code: '+1-284' },
    { code: 'BN', name: 'Brunei', flag: '🇧🇳', phone_code: '+673' },
    { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', phone_code: '+359' },
    { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', phone_code: '+226' },
    { code: 'BI', name: 'Burundi', flag: '🇧🇮', phone_code: '+257' },
    { code: 'KH', name: 'Cambodia', flag: '🇰🇭', phone_code: '+855' },
    { code: 'CM', name: 'Cameroon', flag: '🇨🇲', phone_code: '+237' },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', phone_code: '+1' },
    { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', phone_code: '+238' },
    { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', phone_code: '+1-345' },
    { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', phone_code: '+236' },
    { code: 'TD', name: 'Chad', flag: '🇹🇩', phone_code: '+235' },
    { code: 'CL', name: 'Chile', flag: '🇨🇱', phone_code: '+56' },
    { code: 'CN', name: 'China', flag: '🇨🇳', phone_code: '+86' },
    { code: 'CX', name: 'Christmas Island', flag: '🇨🇽', phone_code: '+61' },
    { code: 'CC', name: 'Cocos Islands', flag: '🇨🇨', phone_code: '+61' },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴', phone_code: '+57' },
    { code: 'KM', name: 'Comoros', flag: '🇰🇲', phone_code: '+269' },
    { code: 'CK', name: 'Cook Islands', flag: '🇨🇰', phone_code: '+682' },
    { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', phone_code: '+506' },
    { code: 'HR', name: 'Croatia', flag: '🇭🇷', phone_code: '+385' },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺', phone_code: '+53' },
    { code: 'CW', name: 'Curacao', flag: '🇨🇼', phone_code: '+599' },
    { code: 'CY', name: 'Cyprus', flag: '🇨🇾', phone_code: '+357' },
    { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', phone_code: '+420' },
    { code: 'CD', name: 'Democratic Republic of the Congo', flag: '🇨🇩', phone_code: '+243' },
    { code: 'DK', name: 'Denmark', flag: '🇩🇰', phone_code: '+45' },
    { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', phone_code: '+253' },
    { code: 'DM', name: 'Dominica', flag: '🇩🇲', phone_code: '+1-767' },
    { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', phone_code: '+1-809' },
    { code: 'TL', name: 'East Timor', flag: '🇹🇱', phone_code: '+670' },
    { code: 'EC', name: 'Ecuador', flag: '🇪🇨', phone_code: '+593' },
    { code: 'EG', name: 'Egypt', flag: '🇪🇬', phone_code: '+20' },
    { code: 'SV', name: 'El Salvador', flag: '🇸🇻', phone_code: '+503' },
    { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', phone_code: '+240' },
    { code: 'ER', name: 'Eritrea', flag: '🇪🇷', phone_code: '+291' },
    { code: 'EE', name: 'Estonia', flag: '🇪🇪', phone_code: '+372' },
    { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', phone_code: '+251' },
    { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰', phone_code: '+500' },
    { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', phone_code: '+298' },
    { code: 'FJ', name: 'Fiji', flag: '🇫🇯', phone_code: '+679' },
    { code: 'FI', name: 'Finland', flag: '🇫🇮', phone_code: '+358' },
    { code: 'FR', name: 'France', flag: '🇫🇷', phone_code: '+33' },
    { code: 'PF', name: 'French Polynesia', flag: '🇵🇫', phone_code: '+689' },
    { code: 'GA', name: 'Gabon', flag: '🇬🇦', phone_code: '+241' },
    { code: 'GM', name: 'Gambia', flag: '🇬🇲', phone_code: '+220' },
    { code: 'GE', name: 'Georgia', flag: '🇬🇪', phone_code: '+995' },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', phone_code: '+49' },
    { code: 'GH', name: 'Ghana', flag: '🇬🇭', phone_code: '+233' },
    { code: 'GI', name: 'Gibraltar', flag: '🇬🇮', phone_code: '+350' },
    { code: 'GR', name: 'Greece', flag: '🇬🇷', phone_code: '+30' },
    { code: 'GL', name: 'Greenland', flag: '🇬🇱', phone_code: '+299' },
    { code: 'GD', name: 'Grenada', flag: '🇬🇩', phone_code: '+1-473' },
    { code: 'GU', name: 'Guam', flag: '🇬🇺', phone_code: '+1-671' },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹', phone_code: '+502' },
    { code: 'GG', name: 'Guernsey', flag: '🇬🇬', phone_code: '+44-1481' },
    { code: 'GN', name: 'Guinea', flag: '🇬🇳', phone_code: '+224' },
    { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', phone_code: '+245' },
    { code: 'GY', name: 'Guyana', flag: '🇬🇾', phone_code: '+592' },
    { code: 'HT', name: 'Haiti', flag: '🇭🇹', phone_code: '+509' },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳', phone_code: '+504' },
    { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', phone_code: '+852' },
    { code: 'HU', name: 'Hungary', flag: '🇭🇺', phone_code: '+36' },
    { code: 'IS', name: 'Iceland', flag: '🇮🇸', phone_code: '+354' },
    { code: 'IN', name: 'India', flag: '🇮🇳', phone_code: '+91' },
    { code: 'ID', name: 'Indonesia', flag: '🇮🇩', phone_code: '+62' },
    { code: 'IR', name: 'Iran', flag: '🇮🇷', phone_code: '+98' },
    { code: 'IQ', name: 'Iraq', flag: '🇮🇶', phone_code: '+964' },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪', phone_code: '+353' },
    { code: 'IM', name: 'Isle of Man', flag: '🇮🇲', phone_code: '+44-1624' },
    { code: 'IL', name: 'Israel', flag: '🇮🇱', phone_code: '+972' },
    { code: 'IT', name: 'Italy', flag: '🇮🇹', phone_code: '+39' },
    { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮', phone_code: '+225' },
    { code: 'JM', name: 'Jamaica', flag: '🇯🇲', phone_code: '+1-876' },
    { code: 'JP', name: 'Japan', flag: '🇯🇵', phone_code: '+81' },
    { code: 'JE', name: 'Jersey', flag: '🇯🇪', phone_code: '+44-1534' },
    { code: 'JO', name: 'Jordan', flag: '🇯🇴', phone_code: '+962' },
    { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', phone_code: '+7' },
    { code: 'KE', name: 'Kenya', flag: '🇰🇪', phone_code: '+254' },
    { code: 'KI', name: 'Kiribati', flag: '🇰🇮', phone_code: '+686' },
    { code: 'XK', name: 'Kosovo', flag: '🇽🇰', phone_code: '+383' },
    { code: 'KW', name: 'Kuwait', flag: '🇰🇼', phone_code: '+965' },
    { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', phone_code: '+996' },
    { code: 'LA', name: 'Laos', flag: '🇱🇦', phone_code: '+856' },
    { code: 'LV', name: 'Latvia', flag: '🇱🇻', phone_code: '+371' },
    { code: 'LB', name: 'Lebanon', flag: '🇱🇧', phone_code: '+961' },
    { code: 'LS', name: 'Lesotho', flag: '🇱🇸', phone_code: '+266' },
    { code: 'LR', name: 'Liberia', flag: '🇱🇷', phone_code: '+231' },
    { code: 'LY', name: 'Libya', flag: '🇱🇾', phone_code: '+218' },
    { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', phone_code: '+423' },
    { code: 'LT', name: 'Lithuania', flag: '🇱🇹', phone_code: '+370' },
    { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', phone_code: '+352' },
    { code: 'MO', name: 'Macau', flag: '🇲🇴', phone_code: '+853' },
    { code: 'MK', name: 'Macedonia', flag: '🇲🇰', phone_code: '+389' },
    { code: 'MG', name: 'Madagascar', flag: '🇲🇬', phone_code: '+261' },
    { code: 'MW', name: 'Malawi', flag: '🇲🇼', phone_code: '+265' },
    { code: 'MY', name: 'Malaysia', flag: '🇲🇾', phone_code: '+60' },
    { code: 'MV', name: 'Maldives', flag: '🇲🇻', phone_code: '+960' },
    { code: 'ML', name: 'Mali', flag: '🇲🇱', phone_code: '+223' },
    { code: 'MT', name: 'Malta', flag: '🇲🇹', phone_code: '+356' },
    { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', phone_code: '+692' },
    { code: 'MR', name: 'Mauritania', flag: '🇲🇷', phone_code: '+222' },
    { code: 'MU', name: 'Mauritius', flag: '🇲🇺', phone_code: '+230' },
    { code: 'YT', name: 'Mayotte', flag: '🇾🇹', phone_code: '+262' },
    { code: 'MX', name: 'Mexico', flag: '🇲🇽', phone_code: '+52' },
    { code: 'FM', name: 'Micronesia', flag: '🇫🇲', phone_code: '+691' },
    { code: 'MD', name: 'Moldova', flag: '🇲🇩', phone_code: '+373' },
    { code: 'MC', name: 'Monaco', flag: '🇲🇨', phone_code: '+377' },
    { code: 'MN', name: 'Mongolia', flag: '🇲🇳', phone_code: '+976' },
    { code: 'ME', name: 'Montenegro', flag: '🇲🇪', phone_code: '+382' },
    { code: 'MS', name: 'Montserrat', flag: '🇲🇸', phone_code: '+1-664' },
    { code: 'MA', name: 'Morocco', flag: '🇲🇦', phone_code: '+212' },
    { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', phone_code: '+258' },
    { code: 'MM', name: 'Myanmar', flag: '🇲🇲', phone_code: '+95' },
    { code: 'NA', name: 'Namibia', flag: '🇳🇦', phone_code: '+264' },
    { code: 'NR', name: 'Nauru', flag: '🇳🇷', phone_code: '+674' },
    { code: 'NP', name: 'Nepal', flag: '🇳🇵', phone_code: '+977' },
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱', phone_code: '+31' },
    { code: 'NC', name: 'New Caledonia', flag: '🇳🇨', phone_code: '+687' },
    { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', phone_code: '+64' },
    { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', phone_code: '+505' },
    { code: 'NE', name: 'Niger', flag: '🇳🇪', phone_code: '+227' },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', phone_code: '+234' },
    { code: 'NU', name: 'Niue', flag: '🇳🇺', phone_code: '+683' },
    { code: 'NF', name: 'Norfolk Island', flag: '🇳🇫', phone_code: '+672' },
    { code: 'KP', name: 'North Korea', flag: '🇰🇵', phone_code: '+850' },
    { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', phone_code: '+1-670' },
    { code: 'NO', name: 'Norway', flag: '🇳🇴', phone_code: '+47' },
    { code: 'OM', name: 'Oman', flag: '🇴🇲', phone_code: '+968' },
    { code: 'PK', name: 'Pakistan', flag: '🇵🇰', phone_code: '+92' },
    { code: 'PW', name: 'Palau', flag: '🇵🇼', phone_code: '+680' },
    { code: 'PS', name: 'Palestine', flag: '🇵🇸', phone_code: '+970' },
    { code: 'PA', name: 'Panama', flag: '🇵🇦', phone_code: '+507' },
    { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', phone_code: '+675' },
    { code: 'PY', name: 'Paraguay', flag: '🇵🇾', phone_code: '+595' },
    { code: 'PE', name: 'Peru', flag: '🇵🇪', phone_code: '+51' },
    { code: 'PH', name: 'Philippines', flag: '🇵🇭', phone_code: '+63' },
    { code: 'PN', name: 'Pitcairn', flag: '🇵🇳', phone_code: '+64' },
    { code: 'PL', name: 'Poland', flag: '🇵🇱', phone_code: '+48' },
    { code: 'PT', name: 'Portugal', flag: '🇵🇹', phone_code: '+351' },
    { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', phone_code: '+1-787' },
    { code: 'QA', name: 'Qatar', flag: '🇶🇦', phone_code: '+974' },
    { code: 'CG', name: 'Republic of the Congo', flag: '🇨🇬', phone_code: '+242' },
    { code: 'RE', name: 'Reunion', flag: '🇷🇪', phone_code: '+262' },
    { code: 'RO', name: 'Romania', flag: '🇷🇴', phone_code: '+40' },
    { code: 'RU', name: 'Russia', flag: '🇷🇺', phone_code: '+7' },
    { code: 'RW', name: 'Rwanda', flag: '🇷🇼', phone_code: '+250' },
    { code: 'BL', name: 'Saint Barthelemy', flag: '🇧🇱', phone_code: '+590' },
    { code: 'SH', name: 'Saint Helena', flag: '🇸🇭', phone_code: '+290' },
    { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', phone_code: '+1-869' },
    { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', phone_code: '+1-758' },
    { code: 'MF', name: 'Saint Martin', flag: '🇲🇫', phone_code: '+590' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', phone_code: '+508' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', phone_code: '+1-784' },
    { code: 'WS', name: 'Samoa', flag: '🇼🇸', phone_code: '+685' },
    { code: 'SM', name: 'San Marino', flag: '🇸🇲', phone_code: '+378' },
    { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', phone_code: '+239' },
    { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', phone_code: '+966' },
    { code: 'SN', name: 'Senegal', flag: '🇸🇳', phone_code: '+221' },
    { code: 'RS', name: 'Serbia', flag: '🇷🇸', phone_code: '+381' },
    { code: 'SC', name: 'Seychelles', flag: '🇸🇨', phone_code: '+248' },
    { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', phone_code: '+232' },
    { code: 'SG', name: 'Singapore', flag: '🇸🇬', phone_code: '+65' },
    { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽', phone_code: '+1-721' },
    { code: 'SK', name: 'Slovakia', flag: '🇸🇰', phone_code: '+421' },
    { code: 'SI', name: 'Slovenia', flag: '🇸🇮', phone_code: '+386' },
    { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', phone_code: '+677' },
    { code: 'SO', name: 'Somalia', flag: '🇸🇴', phone_code: '+252' },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦', phone_code: '+27' },
    { code: 'KR', name: 'South Korea', flag: '🇰🇷', phone_code: '+82' },
    { code: 'SS', name: 'South Sudan', flag: '🇸🇸', phone_code: '+211' },
    { code: 'ES', name: 'Spain', flag: '🇪🇸', phone_code: '+34' },
    { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', phone_code: '+94' },
    { code: 'SD', name: 'Sudan', flag: '🇸🇩', phone_code: '+249' },
    { code: 'SR', name: 'Suriname', flag: '🇸🇷', phone_code: '+597' },
    { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯', phone_code: '+47' },
    { code: 'SZ', name: 'Swaziland', flag: '🇸🇿', phone_code: '+268' },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪', phone_code: '+46' },
    { code: 'CH', name: 'Switzerland', flag: '🇨🇭', phone_code: '+41' },
    { code: 'SY', name: 'Syria', flag: '🇸🇾', phone_code: '+963' },
    { code: 'TW', name: 'Taiwan', flag: '🇹🇼', phone_code: '+886' },
    { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', phone_code: '+992' },
    { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', phone_code: '+255' },
    { code: 'TH', name: 'Thailand', flag: '🇹🇭', phone_code: '+66' },
    { code: 'TG', name: 'Togo', flag: '🇹🇬', phone_code: '+228' },
    { code: 'TK', name: 'Tokelau', flag: '🇹🇰', phone_code: '+690' },
    { code: 'TO', name: 'Tonga', flag: '🇹🇴', phone_code: '+676' },
    { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', phone_code: '+1-868' },
    { code: 'TN', name: 'Tunisia', flag: '🇹🇳', phone_code: '+216' },
    { code: 'TR', name: 'Turkey', flag: '🇹🇷', phone_code: '+90' },
    { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', phone_code: '+993' },
    { code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨', phone_code: '+1-649' },
    { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', phone_code: '+688' },
    { code: 'VI', name: 'U.S. Virgin Islands', flag: '🇻🇮', phone_code: '+1-340' },
    { code: 'UG', name: 'Uganda', flag: '🇺🇬', phone_code: '+256' },
    { code: 'UA', name: 'Ukraine', flag: '🇺🇦', phone_code: '+380' },
    { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', phone_code: '+971' },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', phone_code: '+44' },
    { code: 'US', name: 'United States', flag: '🇺🇸', phone_code: '+1' },
    { code: 'UY', name: 'Uruguay', flag: '🇺🇾', phone_code: '+598' },
    { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', phone_code: '+998' },
    { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', phone_code: '+678' },
    { code: 'VA', name: 'Vatican', flag: '🇻🇦', phone_code: '+379' },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪', phone_code: '+58' },
    { code: 'VN', name: 'Vietnam', flag: '🇻🇳', phone_code: '+84' },
    { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫', phone_code: '+681' },
    { code: 'EH', name: 'Western Sahara', flag: '🇪🇭', phone_code: '+212' },
    { code: 'YE', name: 'Yemen', flag: '🇾🇪', phone_code: '+967' },
    { code: 'ZM', name: 'Zambia', flag: '🇿🇲', phone_code: '+260' },
    { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', phone_code: '+263' }
];

async function seedCountries() {
    console.log('Connecting to database...');
    await pool.query('BEGIN');

    try {
        console.log('Creating countries table...');
        await pool.query(`
      CREATE TABLE IF NOT EXISTS countries (
        id SERIAL PRIMARY KEY,
        code VARCHAR(2) NOT NULL UNIQUE,
        name VARCHAR(100) NOT NULL,
        flag VARCHAR(10),
        phone_code VARCHAR(20),
        is_supported BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

        console.log('Clearing existing countries...');
        await pool.query('TRUNCATE table countries RESTART IDENTITY');

        console.log(`Seeding ${countries.length} countries...`);
        const values = countries.map((c, i) =>
            `('${c.code}', '${c.name.replace(/'/g, "''")}', '${c.flag}', '${c.phone_code}')`
        ).join(',');

        await pool.query(`
      INSERT INTO countries (code, name, flag, phone_code)
      VALUES ${values}
      ON CONFLICT (code) DO UPDATE 
      SET name = EXCLUDED.name, 
          flag = EXCLUDED.flag, 
          phone_code = EXCLUDED.phone_code,
          updated_at = NOW();
    `);

        await pool.query('COMMIT');
        console.log('✅ Countries seeded successfully');
    } catch (error) {
        await pool.query('ROLLBACK');
        console.error('❌ Error seeding countries:', error);
    } finally {
        pool.end();
    }
}

seedCountries();
